<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-15 at 17:29:57.
 */
class AccountControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AccountController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AccountController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AccountController::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::profileAction
     * @todo   Implement testProfileAction().
     */
    public function testProfileAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::cancelBookmarkAction
     * @todo   Implement testCancelBookmarkAction().
     */
    public function testCancelBookmarkAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::bookmarkUserAction
     * @todo   Implement testBookmarkUserAction().
     */
    public function testBookmarkUserAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::testimonialsAction
     * @todo   Implement testTestimonialsAction().
     */
    public function testTestimonialsAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::portfolioAction
     * @todo   Implement testPortfolioAction().
     */
    public function testPortfolioAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::portfolioDetailsAction
     * @todo   Implement testPortfolioDetailsAction().
     */
    public function testPortfolioDetailsAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::deletePortfolioAction
     * @todo   Implement testDeletePortfolioAction().
     */
    public function testDeletePortfolioAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::inboxAction
     * @todo   Implement testInboxAction().
     */
    public function testInboxAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::getReplyMessageForm
     * @todo   Implement testGetReplyMessageForm().
     */
    public function testGetReplyMessageForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::projectInboxAction
     * @todo   Implement testProjectInboxAction().
     */
    public function testProjectInboxAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::deleteInboxMessageAction
     * @todo   Implement testDeleteInboxMessageAction().
     */
    public function testDeleteInboxMessageAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::outboxAction
     * @todo   Implement testOutboxAction().
     */
    public function testOutboxAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::deleteOutboxMessageAction
     * @todo   Implement testDeleteOutboxMessageAction().
     */
    public function testDeleteOutboxMessageAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::projectOutboxAction
     * @todo   Implement testProjectOutboxAction().
     */
    public function testProjectOutboxAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::getAddPortfolioForm
     * @todo   Implement testGetAddPortfolioForm().
     */
    public function testGetAddPortfolioForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::addPortfolioAction
     * @todo   Implement testAddPortfolioAction().
     */
    public function testAddPortfolioAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::getEditPortfolioForm
     * @todo   Implement testGetEditPortfolioForm().
     */
    public function testGetEditPortfolioForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::editPortfolioAction
     * @todo   Implement testEditPortfolioAction().
     */
    public function testEditPortfolioAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::getEditProfileForm
     * @todo   Implement testGetEditProfileForm().
     */
    public function testGetEditProfileForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::editProfileAction
     * @todo   Implement testEditProfileAction().
     */
    public function testEditProfileAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
