<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-15 at 17:36:48.
 */
class IndexControllerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var IndexController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new IndexController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers IndexController::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::getLoginForm
     * @todo   Implement testGetLoginForm().
     */
    public function testGetLoginForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::loginAction
     * @todo   Implement testLoginAction().
     */
    public function testLoginAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::logoutAction
     * @todo   Implement testLogoutAction().
     */
    public function testLogoutAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::getSignupForm
     * @todo   Implement testGetSignupForm().
     */
    public function testGetSignupForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::signupAction
     * @todo   Implement testSignupAction().
     */
    public function testSignupAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::getPaypalPaymentForm
     * @todo   Implement testGetPaypalPaymentForm().
     */
    public function testGetPaypalPaymentForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::paypalPaymentAction
     * @todo   Implement testPaypalPaymentAction().
     */
    public function testPaypalPaymentAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::premiumSuccessfulAction
     * @todo   Implement testPremiumSuccessfulAction().
     */
    public function testPremiumSuccessfulAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IndexController::premiumUnsuccessfulAction
     * @todo   Implement testPremiumUnsuccessfulAction().
     */
    public function testPremiumUnsuccessfulAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
